apiVersion: apps/v1
kind: Deployment
metadata:
  name: sws-example-java-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sws-example-java-petclinic
  template:
    metadata:
      labels:
        app: sws-example-java-petclinic
    spec:
      containers:
        - name: sws-example-java-petclinic
          image: angadisachin2/otel-java-postgress-poc:latest
          ports:
          - containerPort: 9966
          env:
            - name: PORT
              value: "9966"
            # - name: OTEL_RESOURCE_ATTRIBUTES
            #   value: "service.name=analytics-service"
            # - name: OTEL_EXPORTER
            #   value: "otlp"
          readinessProbe:
            tcpSocket:
              port: 9966
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sws-example-java-petclinic
spec:
  type: LoadBalancer
  selector:
    app: sws-example-java-petclinic
  ports:
    - name: http
      port: 80
      targetPort: 9966