apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: otel-collector
data:
  otel-collector-config.yml: |
    extensions:
      health_check:
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:55680

      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 10s
            static_configs:
            - targets: ['0.0.0.0:8888']

    processors:
      batch:
            
    exporters:
      otlp/data-prepper:
        endpoint: data-prepper.data-prepper.svc.cluster.local:21890
        tls:
          insecure: true

      logging:
        logLevel: debug
      

    service:
      extensions: [health_check,pprof,zpages]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp/data-prepper]

        metrics:
          receivers: [otlp, prometheus]
          processors: [batch]
          exporters: [logging]

  demo-data-prepper.crt: | 
    -----BEGIN CERTIFICATE-----
    MIICqjCCAZICCQDBYJxuuzsbczANBgkqhkiG9w0BAQsFADAXMRUwEwYDVQQDDAxk
    YXRhLXByZXBwZXIwHhcNMjAxMTMwMTc0NDM4WhcNMzAxMTI4MTc0NDM4WjAXMRUw
    EwYDVQQDDAxkYXRhLXByZXBwZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDBuSTI3oz9ZJRiVQCdTfbQlG9TWCXwuIjjJcVwvgVjhIuj5VLEOWUpC8nr
    be4/3ttGLuqOBViLlw2aelN7ZANgFy33ONF7kDh4xFMp4rZdFKxCOsmUpbSD7hRf
    8mVRFv30bx9//bVjLP8qi2QKuHc8WOevMsdNENFI6BgiI52EoVPyYJIIMaE2ripG
    qkQVn04Tk+rWz3zQ+NyOcExow98+pxMIjAanMUELTpMjQCWq2HtV2nnqcfqqNCae
    ig7NSDRvQtPL84Fjy7y4B1pS558hBmfOyZcGHo/gxLxQmvb1UKy4bcL7Kd8H3aNr
    LZ8zsr+he3cM9a7SZbiilALdcv0NAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAKvw
    fLiflX0Wd54ExsQvLvwZbrVU0z110h2N+E7SXt9K4NhHsANsX2mWxbqU/0YMYQpo
    fPO0XJSqmo28YD/eyKEazJg7tFISEqQ5gfWZM8BkfHcjbHMixtRDm6SpNzfeQT97
    C0zZo5kAD4d0Y3FwVjQ5FkvlmM6rCaJ0NyvZBUJseCsWpZsV2vF0QbMQcQ0lxjqY
    Vxs8Cnwp9bfF7ZP3i5KD5JxtVm80g6MIQdoYDQqtMjhZ8rCg5e1S6DbPnLRlmXkz
    4cFfD4V/7+ldSpEt38QBtCFWalfem+4dtbEX8FoTciNZfCkeUotpO2jPS1IzzghA
    yy6bLJd2MHl8AnGRdQg=
    -----END CERTIFICATE-----
  

    
